// Class: ReadNeuroBayes
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : NeuroBayes::NeuroBayes
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/09       [336393]
Creator        : skloibho
Date           : Wed Nov 12 17:48:43 2014
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/user/s/skloibho/nb1
Training events: 11362
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
Analysis: "False" [You may chose whether you want to run the NeuroBayes analysis macro or not (default=yes)]
Regularisation: "OFF" [Type of regularisation: Possible choices are: OFF , REG (default), ARD , ASR, ALL.]
Preprocessing: "22" [Type of preprocessing: Refer to NeuroBayes-Howto A.1 for Details.]
LossFunc: "ENTROPY" [Type of loss-function: Possible choices are ENTROPY (default), QUADRATIC and COMBINED .]
ShapeTreat: "INCL" [Shape treatment: Possible choices are OFF, INCL, MARGINAL, DIAG and TOL.]
NtrainingIter: "220" [Number of training iterations: This parameter defines the number of training iterations.]
LimitLearingSpeed: "2.000000e+00" [Limit learning speed: The maximal learning speed may be limited]
NBIndiPreproFlagList: "24,24,25,23,12,23,14" [Set individual preprocessing flags in a coma seperated string,  e.g. 12,12,12,12. See NeuroBayes-HowTo for infos]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
Momentum: "0.000000e+00" [Optionally, a momentum can be specified for the training.]
WeightUpdate: "200" [Weight update: Normally, the weights are updated every 200 events.]
LearingSpeed: "1.000000e+00" [Increase learning speed by a multiplicative factor.]
TrainingMethod: "NOBFGS" [Training Method: It is possible to use the BFGS algorithm]
NBIndiPreproFlagByVarname: "" [Set individual preprocessing flags in a coma seperated string, e.g. varname1=<PreproFlag>.<1stPreproparam>.<2ndPreproparam>...,varname2=19,...]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
svfit_mass                    svfit_mass                    svfit_mass                    m_{sv}                        GeV                               'F'    [41.3561477661,1078.41101074]
jdeta                         jdeta                         jdeta                         #Delta#eta_{j1j2}             ""                                'F'    [2.00004887581,8.22789287567]
pt_tot                        pt_tot                        pt_tot                        p_{T}^{tot}                   GeV                               'F'    [0.264827102423,1173.34973145]
met_centrality                met_centrality                met_centrality                E_{T}^{miss} centrality       ""                                'F'    [-1.41421353817,1.41421353817]
lep_etacentrality             lep_etacentrality             lep_etacentrality             lep #eta centrality           ""                                'F'    [5.39648006281e-08,1]
pt_sum                        pt_sum                        pt_sum                        p_{T}^{sum}                   GeV                               'F'    [137.536331177,1461.9798584]
mvis                          mvis                          mvis                          m_{vis}                       GeV                               'F'    [30.063337326,485.678894043]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadNeuroBayes : public IClassifierReader {

 public:

   // constructor
   ReadNeuroBayes( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadNeuroBayes" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "svfit_mass", "jdeta", "pt_tot", "met_centrality", "lep_etacentrality", "pt_sum", "mvis" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 41.3561477661133;
      fVmax[0] = 1078.41101074219;
      fVmin[1] = 2.00004887580872;
      fVmax[1] = 8.22789287567139;
      fVmin[2] = 0.264827102422714;
      fVmax[2] = 1173.34973144531;
      fVmin[3] = -1.41421353816986;
      fVmax[3] = 1.41421353816986;
      fVmin[4] = 5.39648006281368e-08;
      fVmax[4] = 1;
      fVmin[5] = 137.536331176758;
      fVmax[5] = 1461.97985839844;
      fVmin[6] = 30.0633373260498;
      fVmax[6] = 485.678894042969;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadNeuroBayes() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   inline double ReadNeuroBayes::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
